#!/bin/bash

# https://docs.docker.com/docker-cloud/builds/advanced/#build-hook-examples

VERSION=$(git describe --always --tags)
VCS_REF=$(git rev-parse HEAD)
VCS_URL=$(git remote get-url origin)
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

docker build \
  --build-arg VERSION=$VERSION \
  --build-arg VCS_REF=$VCS_REF \
  --build-arg VCS_URL=$VCS_URL \
  --build-arg BUILD_DATE=$BUILD_DATE \
  -t $IMAGE_NAME .